# Generated by Django 5.0.2 on 2024-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(db_column='contraseña', max_length=128, verbose_name='Contraseña'),
        ),
    ]
