# Generated by Django 5.0.2 on 2024-03-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correoelectronico',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
