# Generated by Django 5.0.2 on 2024-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_vehiculos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='estadoticket',
            field=models.CharField(blank=True, choices=[('Reservado', 'RESERVADO'), ('Usado', 'USADO')], default='Reservado', max_length=10, null=True, verbose_name='Estado'),
        ),
    ]
