# Generated by Django 5.0.2 on 2024-04-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_tickets_estadoticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='vehiculoid',
            field=models.ForeignKey(blank=True, db_column='vehiculoid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vehiculos', verbose_name='ID de Vehiculo'),
        ),
    ]
