# Generated by Django 5.0.2 on 2024-04-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tickets_viajeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='viajeid',
            field=models.ForeignKey(blank=True, db_column='viajeid', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.viajes', verbose_name='ID del Viaje'),
        ),
    ]
