# Generated by Django 5.0.2 on 2024-04-04 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_tickets_viajeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='fechareservacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Reservación'),
        ),
        migrations.CreateModel(
            name='ClienteFormaDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_realizado', models.BooleanField(default=False, verbose_name='Pago Realizado')),
                ('stripe_checkout_id', models.CharField(max_length=100, verbose_name='ID de Stripe Checkout')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
            ],
            options={
                'verbose_name': 'Cliente Forma de Pago',
                'verbose_name_plural': 'Clientes Forma de Pago',
            },
        ),
    ]
