# Generated by Django 5.0.2 on 2024-04-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_tickets_fechareservacion_clienteformadepago'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clienteformadepago',
            table='clienteformadepago',
        ),
    ]
