# Generated by Django 5.0.9 on 2024-12-03 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_usuarios_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='anofabricacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='conductorid',
            field=models.ForeignKey(blank=True, db_column='conductorid', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.conductores', verbose_name='ID del Conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'DISPONIBLE'), ('Ocupado', 'OCUPADO'), ('Mantenimiento', 'MANTENIMIENTO')], default='Disponible', max_length=15, verbose_name='Estado'),
        ),
    ]
